version: "3.9"

services:
  db:
    image: mongo
    networks:
      - mongo-cluster
    volumes:
      - ./init-repl-set.sh:/docker-entrypoint-initdb.d/init-repl-set.sh
    command: mongod --replSet replset
    ports:
      - "27017:27017"
  app:
    image: 'readingisgood:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    external_links:
      - db:db
    ports:
      - "8080:8080"
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    driver: bridge
